version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    entrypoint: ["/entrypoint.sh"]
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=christakadje20@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/etc/traefik/acme.json
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - laravel_network

  app:
    image: christ903/thepalatin307:latest
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - APP_ENV=production
      - APP_URL=https://thepalatin.com
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`thepalatin.com`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"
      - "traefik.http.routers.app.middlewares=redirect-to-https@file"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge


# services:
#   traefik:
#     image: traefik:v2.10
#     container_name: traefik
#     command:
#       - "--api.dashboard=true"
#       - "--providers.docker=true"
#       - "--providers.docker.exposedbydefault=false"
#       - "--entrypoints.web.address=:80"
#       - "--entrypoints.websecure.address=:443"
#       - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
#       - "--certificatesresolvers.letsencrypt.acme.email=christakadje20@gmail.com"
#       - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
#       - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
#       - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./acme.json:/etc/traefik/acme.json
#     networks:
#       - laravel_network

#   app:
#     image: christ903/thepalatin307:latest
#     container_name: laravel_app
#     restart: unless-stopped
#     depends_on:
#       - traefik
#     environment:
#       - APP_ENV=production
#       - APP_URL=https://thepalatin.com
#       - APP_DEBUG=false
#       - APP_KEY=${APP_KEY}
#       - DB_CONNECTION=pgsql
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT:-5432}
#       - DB_DATABASE=${DB_DATABASE}
#       - DB_USERNAME=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.laravel.rule=Host(`thepalatin.com`)"
#       - "traefik.http.routers.laravel.entrypoints=websecure"
#       - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
#       - "traefik.http.services.laravel.loadbalancer.server.port=80"  
#     networks:
#       - laravel_network

# networks:
#   laravel_network:
#     driver: bridge
# version: '3.12'

# services:
#   traefik:
#     image: traefik:v2.10
#     container_name: traefik
#     command:
#       - "--api.dashboard=true"
#       - "--providers.docker=true"
#       - "--providers.docker.exposedbydefault=false"
#       - "--entrypoints.web.address=:80"
#       - "--entrypoints.websecure.address=:443"
#       - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
#       - "--certificatesresolvers.letsencrypt.acme.email=christakadje20@gmail.com"
#       - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
#       - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
#       - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./acme.json:/etc/traefik/acme.json
#     labels:
#       - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
#     networks:
#       - laravel_network
#   # Service PHP + Laravel
#   app:
#     image: christ903/thepalatin307:latest
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     volumes:
#       - .:/var/www/html
#     environment:
#       - APP_ENV=production
#       - APP_URL=https://thepalatin.com
#       - APP_DEBUG=false
#       - APP_KEY=${APP_KEY}
#       - DB_CONNECTION=pgsql
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=5432
#       - DB_DATABASE=${DB_DATABASE}
#       - DB_USERNAME=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.laravel.rule=Host(`thepalatin.com`)"
#       - "traefik.http.routers.laravel.entrypoints=websecure"
#       - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
#       - "traefik.http.routers.laravel-http.rule=Host(`thepalatin.com`)"
#       - "traefik.http.routers.laravel-http.entrypoints=web"
#       - "traefik.http.routers.laravel-http.middlewares=redirect-to-https"
#       - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
#       - "traefik.http.services.laravel.loadbalancer.server.port=80"
#     networks:
#       - laravel_network
#     depends_on:
#       - db

#   # Service PostgreSQL
#   db:
#     image: postgres:15
#     container_name: laravel_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ${DB_DATABASE}
#       POSTGRES_USER: ${DB_USERNAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - laravel_network

# networks:
#   laravel_network:
#     driver: bridge

# volumes:
#   postgres_data:

# Version original
# version: '3.12'

# services:
#   # Service PHP + Laravel
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     restart: unless-stopped
#     ports:
#       - 80:80
#     volumes:
#       - .:/var/www/html
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_DATABASE=${DB_DATABASE}
#       - DB_USERNAME=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#     networks:
#       - laravel_network
#     depends_on:
#       - db

#   # Service PostgreSQL
#   db:
#     image: postgres:15-alpine
#     container_name: laravel_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ${DB_DATABASE}
#       POSTGRES_USER: ${DB_USERNAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - laravel_network

# networks:
#   laravel_network:
#     driver: bridge

# volumes:
#   postgres_data:

