entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: false  # sécurise l’accès au dashboard, activé via label si besoin

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: christakadje20@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
