# entryPoints:
#   web:
#     address: ":80"

#   websecure:
#     address: ":443"

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: christakadje20@gmail.com
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web

# providers:
#   docker:
#     exposedByDefault: false

# http:
#   middlewares:
#     redirect-to-https:
#       redirectScheme:
#         scheme: https
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: christakadje20@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
